"""
AuthentiText — AI-Generated Essay Detector
Streamlit frontend application.

Run with:  streamlit run app.py
Requires: outputs/best_model.pkl and outputs/tfidf_vectorizer.pkl
          (produced by AuthentiText_AI_Essay_Detection.ipynb)
"""

import re
import os
import joblib
import numpy as np
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt

# --------------------------------------------------------------------------
# Page configuration
# --------------------------------------------------------------------------
st.set_page_config(
    page_title="AuthentiText | AI Essay Detector",
    page_icon="📝",
    layout="wide",
    initial_sidebar_state="expanded",
)

MODEL_PATH = "outputs/best_model.pkl"
VECTORIZER_PATH = "outputs/tfidf_vectorizer.pkl"
MODEL_NAME_PATH = "outputs/model_name.txt"


# --------------------------------------------------------------------------
# Text cleaning (must mirror the notebook's preprocessing exactly)
# --------------------------------------------------------------------------
def clean_text(text: str) -> str:
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+", " ", text)
    text = re.sub(r"[^a-z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


# --------------------------------------------------------------------------
# Cached resource loading
# --------------------------------------------------------------------------
@st.cache_resource
def load_artifacts():
    if not (os.path.exists(MODEL_PATH) and os.path.exists(VECTORIZER_PATH)):
        return None, None, None
    model = joblib.load(MODEL_PATH)
    vectorizer = joblib.load(VECTORIZER_PATH)
    model_name = "Model"
    if os.path.exists(MODEL_NAME_PATH):
        with open(MODEL_NAME_PATH) as f:
            model_name = f.read().strip()
    return model, vectorizer, model_name


def predict(text, model, vectorizer):
    cleaned = clean_text(text)
    if len(cleaned.strip()) == 0:
        return None, None
    vec = vectorizer.transform([cleaned])
    pred = model.predict(vec)[0]
    proba = model.predict_proba(vec)[0]
    return pred, proba


def text_stats(text: str) -> dict:
    words = text.split()
    sentences = re.split(r"[.!?]+", text)
    sentences = [s for s in sentences if s.strip()]
    word_count = len(words)
    char_count = len(text)
    sentence_count = max(len(sentences), 1)
    avg_word_len = round(char_count / word_count, 2) if word_count else 0
    avg_sentence_len = round(word_count / sentence_count, 2) if sentence_count else 0
    return {
        "Word Count": word_count,
        "Character Count": char_count,
        "Sentence Count": sentence_count,
        "Avg. Word Length": avg_word_len,
        "Avg. Words / Sentence": avg_sentence_len,
    }


# --------------------------------------------------------------------------
# Sidebar
# --------------------------------------------------------------------------
with st.sidebar:
    st.markdown("## 📝 AuthentiText")
    st.markdown("**AI-Generated Essay Detector**")
    st.markdown("---")
    st.markdown(
        """
        This tool uses a machine learning model trained on **29,000+ essays**
        to predict whether a piece of writing was written by a **human** or
        **generated by an AI language model**.

        ### How it works
        1. Paste or type an essay in the text box
        2. The text is cleaned and converted into TF-IDF features
        3. A trained classifier predicts the label and confidence
        """
    )
    st.markdown("---")
    st.markdown("### ⚠️ Disclaimer")
    st.caption(
        "This is an educational project. Predictions are probabilistic and "
        "should not be used as sole evidence in academic integrity or "
        "disciplinary decisions."
    )
    st.markdown("---")
    st.caption("Built with Streamlit · scikit-learn · TF-IDF")

# --------------------------------------------------------------------------
# Load model
# --------------------------------------------------------------------------
model, vectorizer, model_name = load_artifacts()

# --------------------------------------------------------------------------
# Header
# --------------------------------------------------------------------------
st.title("📝 AuthentiText: AI-Generated Essay Detector")
st.markdown(
    "Detect whether an essay was **written by a human** or **generated by an AI model** "
    "(e.g. ChatGPT) using a trained NLP classifier."
)

if model is None:
    st.error(
        "⚠️ Model artifacts not found. Please run "
        "`AuthentiText_AI_Essay_Detection.ipynb` first to train the model — "
        "this generates `outputs/best_model.pkl` and `outputs/tfidf_vectorizer.pkl`."
    )
    st.stop()
else:
    st.success(f"✅ Model loaded: **{model_name}** (trained on 29,145 essays)")

st.markdown("---")

# --------------------------------------------------------------------------
# Main tabs
# --------------------------------------------------------------------------
tab1, tab2, tab3, tab4 = st.tabs(
    ["🔍 Single Essay Check", "📂 Batch Check (CSV)", "📊 Insights & Model Performance", "ℹ️ About the Project"]
)

# ============================== TAB 1 ====================================
with tab1:
    col_input, col_result = st.columns([1.3, 1])

    with col_input:
        st.subheader("Paste your essay")
        sample_options = {
            "— Select a sample —": "",
            "Sample: Human-style essay": (
                "I remember the first time I visited my grandmother's farm during "
                "summer break. The smell of fresh hay and the sound of chickens "
                "in the yard made me feel calm in a way the city never did. My "
                "cousins and I would spend hours building forts out of old wood "
                "planks, arguing about whose fort was better, then forgetting the "
                "argument entirely once dinner was ready. Looking back now, I "
                "realize those messy, unplanned afternoons taught me more about "
                "patience and creativity than any classroom ever did."
            ),
            "Sample: AI-style essay": (
                "In today's rapidly evolving digital landscape, the integration of "
                "artificial intelligence into everyday life has become increasingly "
                "prevalent. This essay explores the multifaceted implications of "
                "AI adoption, examining both its benefits and challenges. On one "
                "hand, AI systems offer unprecedented efficiency and convenience, "
                "streamlining processes across various industries. On the other "
                "hand, concerns regarding data privacy, job displacement, and "
                "ethical considerations continue to warrant careful attention. In "
                "conclusion, a balanced approach to AI implementation is essential "
                "for maximizing societal benefit while mitigating potential risks."
            ),
        }
        chosen_sample = st.selectbox("Try a sample essay (optional):", list(sample_options.keys()))

        default_text = sample_options[chosen_sample]
        user_text = st.text_area(
            "Essay text",
            value=default_text,
            height=320,
            placeholder="Paste an essay here (at least a few sentences for a reliable result)...",
            label_visibility="collapsed",
        )

        analyze_clicked = st.button("🔍 Analyze Essay", type="primary", use_container_width=True)

    with col_result:
        st.subheader("Result")
        if analyze_clicked:
            if not user_text or len(user_text.strip()) < 10:
                st.warning("Please enter a longer piece of text (at least a full sentence).")
            else:
                pred, proba = predict(user_text, model, vectorizer)
                if pred is None:
                    st.warning("Could not process this input. Please try different text.")
                else:
                    ai_prob = proba[1]
                    human_prob = proba[0]

                    if pred == 1:
                        st.error(f"### 🤖 Likely AI-Generated")
                    else:
                        st.success(f"### 🧑 Likely Human-Written")

                    st.metric("AI-Generated Probability", f"{ai_prob*100:.1f}%")

                    fig, ax = plt.subplots(figsize=(5, 1.2))
                    ax.barh([0], [human_prob], color="#4C72B0", label="Human")
                    ax.barh([0], [ai_prob], left=[human_prob], color="#DD8452", label="AI-Generated")
                    ax.set_xlim(0, 1)
                    ax.set_yticks([])
                    ax.set_xlabel("Probability")
                    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.6), ncol=2, frameon=False)
                    for spine in ["top", "right", "left"]:
                        ax.spines[spine].set_visible(False)
                    st.pyplot(fig, use_container_width=True)

                    st.markdown("#### Text Statistics")
                    stats = text_stats(user_text)
                    stats_df = pd.DataFrame(stats.items(), columns=["Metric", "Value"])
                    st.dataframe(stats_df, hide_index=True, use_container_width=True)
        else:
            st.info("Enter or select an essay and click **Analyze Essay** to see the prediction.")

# ============================== TAB 2 ====================================
with tab2:
    st.subheader("Batch prediction from a CSV file")
    st.markdown(
        "Upload a CSV file with a column named **`text`** containing one essay per row. "
        "The app will predict a label for every row and let you download the results."
    )

    uploaded_file = st.file_uploader("Upload CSV", type=["csv"])

    if uploaded_file is not None:
        try:
            batch_df = pd.read_csv(uploaded_file)
        except Exception as e:
            st.error(f"Could not read the CSV file: {e}")
            batch_df = None

        if batch_df is not None:
            if "text" not in batch_df.columns:
                st.error("The uploaded CSV must contain a column named `text`.")
            else:
                if st.button("Run Batch Prediction", type="primary"):
                    with st.spinner("Analyzing essays..."):
                        cleaned = batch_df["text"].astype(str).apply(clean_text)
                        vecs = vectorizer.transform(cleaned)
                        preds = model.predict(vecs)
                        probas = model.predict_proba(vecs)[:, 1]

                        batch_df["prediction"] = np.where(preds == 1, "AI-Generated", "Human-Written")
                        batch_df["ai_probability"] = np.round(probas, 4)

                    st.success(f"Analyzed {len(batch_df)} essays.")
                    st.dataframe(
                        batch_df[["text", "prediction", "ai_probability"]].head(50),
                        use_container_width=True,
                    )

                    col_a, col_b = st.columns(2)
                    with col_a:
                        st.metric("Predicted Human", int((preds == 0).sum()))
                    with col_b:
                        st.metric("Predicted AI-Generated", int((preds == 1).sum()))

                    csv_out = batch_df.to_csv(index=False).encode("utf-8")
                    st.download_button(
                        "⬇️ Download Results as CSV",
                        data=csv_out,
                        file_name="authentitext_predictions.csv",
                        mime="text/csv",
                    )
    else:
        st.info("Upload a CSV file to get started, or try the Single Essay Check tab.")

# ============================== TAB 3 ====================================
with tab3:
    st.subheader("Dataset Insights & Model Performance")
    st.markdown(
        "These charts are generated by `AuthentiText_AI_Essay_Detection.ipynb` during training and "
        "saved to the `outputs/` folder. They are loaded here so you can review the EDA and evaluation "
        "results without re-opening the notebook."
    )

    insight_images = [
        ("outputs/class_distribution.png", "Class Distribution",
         "Balance between human-written and AI-generated essays in the training data."),
        ("outputs/word_count_distribution.png", "Word Count Distribution",
         "Essay length (word count) distribution and boxplot comparison by class."),
        ("outputs/stylometric_features.png", "Stylometric Features",
         "Average word length and sentence count distributions by class."),
        ("outputs/wordclouds.png", "Word Clouds",
         "Most frequent words (stopwords removed) for human-written vs. AI-generated essays."),
        ("outputs/model_comparison.png", "Model Comparison",
         "Accuracy, Precision, Recall, F1-Score, and ROC-AUC across all four trained models."),
        ("outputs/confusion_matrix_roc.png", "Confusion Matrix & ROC Curves",
         "Confusion matrix for the best model and ROC curves for all models on the test set."),
        ("outputs/feature_importance.png", "Top Predictive Terms",
         "Words/phrases most indicative of AI-generated vs. human-written text (Logistic Regression coefficients)."),
    ]

    missing = [title for path, title, _ in insight_images if not os.path.exists(path)]

    if len(missing) == len(insight_images):
        st.warning(
            "No saved plots found in `outputs/`. Run all cells in "
            "`AuthentiText_AI_Essay_Detection.ipynb` to generate them."
        )
    else:
        for path, title, desc in insight_images:
            if os.path.exists(path):
                st.markdown(f"#### {title}")
                st.caption(desc)
                st.image(path, use_container_width=True)
                st.markdown("---")
            else:
                st.info(f"'{title}' plot not found — re-run the notebook to generate `{path}`.")

# ============================== TAB 4 ====================================
with tab4:
    st.subheader("About AuthentiText")
    st.markdown(
        """
        **AuthentiText** is an NLP-based classification system that predicts whether
        a piece of written text was authored by a human or generated by an
        AI language model (such as ChatGPT).

        #### Dataset
        - **29,145 essays**, labeled `0` (human-written) or `1` (AI-generated)
        - Sourced from `Training_Essay_Data.csv`

        #### Pipeline
        1. **Text cleaning** — lowercasing, punctuation/number removal, whitespace normalization
        2. **Feature extraction** — TF-IDF vectorization (unigrams + bigrams, 15,000 features)
        3. **Modeling** — Logistic Regression, Multinomial Naive Bayes, Linear SVM, and
           Random Forest were trained and compared
        4. **Selection** — the best model (by F1-score) was saved and is used here for inference

        #### Tech Stack
        - `pandas`, `numpy` — data handling
        - `scikit-learn` — feature extraction & ML models
        - `nltk`, `wordcloud` — text analysis & visualization (in the training notebook)
        - `streamlit` — this interactive web application

        #### Intended Use & Limitations
        This project is built for **educational purposes** to demonstrate an
        end-to-end NLP classification workflow. AI-text detectors are inherently
        imperfect and can be wrong, especially on:
        - Very short text snippets
        - Heavily edited AI text or heavily "AI-like" human writing
        - Text from language models not represented in the training data

        Predictions from this tool **should not be used alone** to make
        academic integrity or disciplinary decisions.
        """
    )

st.markdown("---")
st.caption("AuthentiText — NLP Project | Built with Streamlit & scikit-learn")
